config/routes.rb
Coodle::Application.routes.draw do

  root :to => 'pages#home'

  get    '/new',     :to => 'projects#new'
  post   '/new',     :to => 'projects#create'
  get    '/:secret', :to => 'projects#show'

  post   '/:secret/people',             :to => 'people#create'
  get    '/:secret/people/new',         :to => 'people#new'
  get    '/:secret/people/:name',       :to => 'people#show'
  delete '/:secret/people/:name',       :to => 'people#destroy'
  get    '/:secret/people/:name/edit',  :to => 'people#edit' 
  put    '/:secret/people/:name/edit',  :to => 'people#update'

  get    '/:secret/expenses/:name/new', :to => 'expenses#new'
  post   '/:secret/expenses/:name',     :to => 'expenses#create'  
  delete '/:secret/expenses/:id',       :to => 'expenses#destroy'

  get    '/:secret/expenses/:expense_id', :to => 'peweights#create'  #with url params (query style)
  delete '/:secret/pew/:pew_id', :to => 'peweights#destroy' 

# resources :expenses
end

app/models/person.rb
class Person < ActiveRecord::Base
    validates_presence_of :name, :project
    validates_uniqueness_of :name, :scope => :project_id 
    belongs_to :project 
    has_many :expenses, :dependent=>:destroy

    def totalAmount #amount already payed by this person
        # this probably can be written shorter by smbdy who knows ruby: 
        total=0 
        expenses.each do |exp|
            total+=exp.amount
        end 
        total
    end

    def amountToPay
        #loop over all project expenses, and sum this person's contribution 
        #depending on weights and expense-units
        total=0 
        project.expenses.each do |exp|
            peweight=Peweight.getPeWeight(id,exp.id)
            total+=(pweight * peweight * exp.amount / exp.getUnits)
        end
        total
    end
    def saldo
      amountToPay-totalAmount
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  include ProjectsHelper
  def new
    @project = Project.find_by_secret(params[:secret])
    @person = Person.new    
  end
  def show
    @project = Project.find_by_secret(params[:secret])
    @person = @project.people.find_by_name(params[:name])
    if @person.nil?
      redirect_to project_path 
    end
  end
  def create
    @project = Project.find_by_secret(params[:secret])
    pid = @project.id 
    pers= params[:person]
    @person = Person.new(:project_id=>pid,:name=>pers[:name],:pweight=>pers[:pweight])
    @person.save
    redirect_to project_path 
  end
  def edit
    @person = Person.find_by_name(params[:name])
    if @person.nil?
      redirect_to project_path 
    end
  end
  def destroy
    person = Project.find_by_secret(params[:secret]).people.find_by_name(params[:name])
    person.destroy 
    redirect_to project_path
  end
  def update
    #warning: name could be updated now
    person = Project.find_by_secret(params[:secret]).people.find_by_name(params[:name])
    person.update_attributes(params[:person])
    redirect_to project_path 
  end
end

app/helpers/people_helper.rb
module PeopleHelper
  def person_path(name)
    URI.escape (root_path + params[:secret] + "/people/" + name) 
  end
  def current_person_path
    person_path params[:name]
  end
  def person_edit_path(name)
    person_path(name) + "/edit"
  end
end

app/views/people/edit.html.erb
<h1>Editing person</h1>

<form method="post"> 
  <input name="_method" type="hidden" value="put" /> 

  <div class="field">
    <label for="person_name">Name</label><br />
    <input id="person_name" name="person[name]" size="30" type="text" value="<%=@person.name%>" />
  </div>

  <div class="field">
    <label for="person_pweight">Weight</label><br />
    <input id="person_pweight" name="person[pweight]" size="30" type="text" value="<%=@person.pweight%>" />
  </div>

  <div class="actions">
    <input name="commit" type="submit" value="Update person" />
  </div>
</form>

<%= link_to 'Back to project', project_path %>

app/views/people/new.html.erb
<h1>New person </h1>

<%  
action="/" + @project.secret + "/people"
%>


<form accept-charset="UTF-8" 
action=<%= action %>
class="new_person" id="new_person" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_token" type="hidden" value="zPl7rZ1biip7gQqIrTIj8JymGAqBc5wIG/r5O/BhSeU=" /></div>

  <div class="field">
    <label for="person_name">Name</label><br />
    <input id="person_name" name="person[name]" size="30" type="text" />
  </div>
  <div class="field">
    <label for="person_pweight">Pweight</label><br />
    <input id="person_pweight" name="person[pweight]" size="30" type="text" value="1.0" />
  </div>
  <div class="actions">
    <input name="commit" type="submit" value="Create Person" />
  </div>
</form>

<%= link_to 'Back', root_path + @project.secret %>

app/views/people/show.html.erb
<p> <%= link_to 'Back to project', project_path %> </p>

<p> <b>Name:</b> <%= @person.name %> </p>

<p>
<%= link_to 'Add expense', new_expense_path(@person.name) %>
</p>

<p><b> List of expenses </b> <br> 
To remove expense: click on description link. <br>
To move person between contributers and non-contributers: click on person link. 
</p>

<table>
  <tr><td><b>Description</b></td> <td><b>Amount</b></td> <td><b>Contributers</b></td> <td><b>Non-contributers</b></td>
  </tr>
  <% @person.expenses.each do |exp| %>
    <tr> <td> <%= link_to exp.description, expense_path(exp.id), :confirm=>'Removing expense. Are you sure?', :method=>:delete %> </td> 
         <td> <%= number_to_currency(exp.amount) %> </td> 
         <td> <% exp.getContributers.each do |c| %>
              <% link=root_path + @project.secret + "/expenses/" + exp.id.to_s + "/?person=" + c[:person].id.to_s + "&weight=0" %>
              <%= link_to c[:person].name, link %> 
              <%= " " %>
              <% end %> 
         </td>
         <td> <% exp.getNonContributers.each do |nc| %>
              <% pewid = Peweight.find_by_person_id_and_expense_id(nc[:person].id, exp.id).id %> 
              <% pewLink=root_path + @project.secret + "/pew/" + pewid.to_s %> 
              <%= link_to nc[:person].name, pewLink, :method=>:delete %>
              <%= " " %>
              <% end %> 
         </td>
    </tr>
  <% end %> 
</table>

<p>
Number of expenses: <%=@person.expenses.count %> <br>
Total of expenses: <%=@person.totalAmount %> <br>
</p>

<p>Debug info: <br>
Project Id: <%= @project.id %> <br>
Person Id: <%= @person.id %> <br>

</p>