config/routes.rb
Coodle::Application.routes.draw do

  root :to => 'pages#home'

  get    '/new',     :to => 'projects#new'
  post   '/new',     :to => 'projects#create'
  get    '/:secret', :to => 'projects#show'

  post   '/:secret/people',             :to => 'people#create'
  get    '/:secret/people/new',         :to => 'people#new'
  get    '/:secret/people/:name',       :to => 'people#show'
  delete '/:secret/people/:name',       :to => 'people#destroy'
  get    '/:secret/people/:name/edit',  :to => 'people#edit' 
  put    '/:secret/people/:name/edit',  :to => 'people#update'

  get    '/:secret/expenses/:name/new', :to => 'expenses#new'
  post   '/:secret/expenses/:name',     :to => 'expenses#create'  
  delete '/:secret/expenses/:id',       :to => 'expenses#destroy'

  get    '/:secret/expenses/:expense_id', :to => 'peweights#create'  #with url params (query style)
  delete '/:secret/pew/:pew_id', :to => 'peweights#destroy' 

# resources :expenses
end

app/models/project.rb
class Project < ActiveRecord::Base
    validates_format_of :secret, :with => /\A([a-z0-9]){16}\Z/
    validates_uniqueness_of :secret 
    has_many :people, :dependent=>:destroy
    has_many :expenses, :through=>:people
    after_initialize :auto_secret

    def auto_secret
      if !self.secret
        # create valid secret that is guaranteed to not exist yet
        allowedChars=('a'..'z').to_a + ('0'..'9').to_a
        begin
          newsecret = (1..16).map{ allowedChars[SecureRandom.random_number(allowedChars.length)] }.join
        end until !Project.find_by_secret(newsecret)
        self.secret = newsecret 
      end
    end

    def totalAmount
    # this probably can be written shorter by smbdy who knows ruby:
        total=0
        people.each do |person|
            total+=person.totalAmount 
        end 
        total
    end

    def getPayments
      payments=[]
      #make hash with person_id#saldo
        ids=people.map{|person| person.id}
        sds=people.map{|person| person.saldo}
      saldos=Hash[ids.zip sds]
      #create payments as long as needed    
      while ! allPaymentsDone(saldos)
        payments<<nextPayment(saldos)
      end
      payments
    end

# ---------CORE OF PAYMENT CALC + SOME HELPER METHODS---------------
  def allPaymentsDone(h)
    if h.empty?
       true
    else
      !(getMaxValue(h) > 0.001)
    end
  end
  def nextPayment(h) #h is hash with ids/saldos
    # principle: biggest payer pays to biggest receiver
    # payer values are +, receiver values are -
    payerID=getKeyOfMaxValue(h)
    receiverID=getKeyOfMinValue(h)
    amount=[getMaxValue(h).abs, getMinValue(h).abs].min   
    h[payerID] -= amount
    h[receiverID] += amount
    from=people.find(payerID).name
    to=people.find(receiverID).name
    Payment.new(from,to,amount)
  end

  def getMaxValue(h)
     h.max_by {|k,v| v}[1]
  end
  def getMinValue(h)
     h.min_by {|k,v| v}[1]
  end
  def getKeyOfMaxValue(h)
     h.max_by {|k,v| v}[0]
  end
  def getKeyOfMinValue(h)
     h.min_by {|k,v| v}[0]
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
  end

  def create
    a_new_project = Project.create(:title=>params[:title])
    #TODO: is there a method for this new URL? like new_project_path after scaffolding
    new_url = root_path + a_new_project.secret
    redirect_to new_url
  end

  def show
    @project = Project.find_by_secret(params[:secret]) 
    #TODO: page 'non-existing URL'if project ? guess yes... 
    if @project.nil?
      redirect_to root_path
    else
      @titletemp=@project.secret
    end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_path
    root_path + params[:secret]
  end
end

app/views/projects/new.html.erb
<h1>New project</h1>
<p>Note: after creating new project, save URL of new project, and distribute if needed.</p>

<form method="post">
  <div class="field">
    <label for="project_title">Title</label><br />
    <input id="project_title" name="title" size="100" type="text" />
  </div>
  <div class="actions">
    <input name="commit" type="submit" value="Create Project" />
  </div>
</form>

<%= link_to 'Back', root_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%=@project.title%></h1>

<p>
Project id: <%= @project.id %> <br> 
</p>

<table>
  <b>People:</b> <br>
  <tr>
    <th></th>  <th></th>  <th></th>
  </tr> 
  <% @project.people.each do |person| %>
    <tr><td><%= link_to person.name, person_path(person.name) %> (weight <%= person.pweight %>)</td>
        <td><%= link_to 'Edit', person_edit_path(person.name) %></td>
        <td><%= link_to 'Remove', person_path(person.name), :confirm=>"Removing #{person.name} from project. Are you sure?", 
                                                            :method=>:delete %></td>
    </tr>
  <% end %>
</table>

<p>
<%= link_to 'Add Person', root_path + @project.secret + "/people/new" %>
</p>

<table>
  <b>Expenses:</b> <br>
  <tr>
    <th>Person</th>
    <th>Amount</th>
    <th>Description</th>
    <th>Contributors</th>
    <th></th>
  </tr>
<% @project.expenses.each do |expense| %>
  <tr>
    <td><%= expense.person.name %></td>
    <td><%= expense.amount %></td>
    <td><%= expense.description %></td>
    <td><% contrib=expense.getContributers %>
        <% if contrib.length == @project.people.length 
             contribString = 'All' 
           else
             contribString = ''
             contrib.each{|c| contribString<<( c[:person].name + " ") }
           end
          %>
        <%= contribString %>
        </td>
  </tr>
<% end %>
</table>
<p>
<?%= link_to 'New expense', new_person_expense_path %> 
</p>

<p>
  <b>Overal total: <%= @project.totalAmount %> </b>
</p>

<p>
<b>Calculation results:</b>
</p>
<p>
<% @project.people.each do |person| %>
  <% if person.saldo >= 0
         verb='still to pay'
     else
         verb='to get back'
     end %>
  <%= person.name %> should contribute <%= person.amountToPay.to_f.round(2) %>, 
  has paid <%= person.totalAmount.to_f.round(2) %> already, so has   
  <%=person.saldo.abs.to_f.round(2)%> <%=verb%>. <br>
<% end %>
</p>

<table>
<b>Proposed payments:</b>
  <% @project.getPayments.each do |pmt| %> 
    <tr><td> <%= pmt.from %> pays <%= pmt.amount.round(2) %> to <%= pmt.to %>. </td></tr>
  <% end %> 
</table>